spring.application.name=e-commerce-backend
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Shiv123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=shivamEcommerceBackendJwtSecretKey2026


spring.data.redis.host=redis-14094.c301.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=14094
spring.data.redis.password=adORwug8D0lO7emv32W4X0UYXKZlQCG1

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=order-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer